# -*- coding: utf-8 -*-
# =============================================================================
# File        : tests/test_foreign_keys.py
# Project     : mydborm
# License     : MIT
# Description : Tests for real FOREIGN KEY constraint generation —
#               BaseModel.create_table() emits FOREIGN KEY ... REFERENCES ...
#               for every ForeignKeyField, and the database enforces it.
# =============================================================================

import os
import socket
import pytest
from mydborm import db, BaseModel, IntField, StrField, ForeignKeyField


# ------------------------------------------------------------------ #
#  MySQL models                                                       #
# ------------------------------------------------------------------ #

class FKAuthor(BaseModel):
    __tablename__ = "fk_authors"
    id   = IntField(primary_key=True)
    name = StrField(max_length=100, nullable=False)


class FKBook(BaseModel):
    __tablename__ = "fk_books"
    id        = IntField(primary_key=True)
    title     = StrField(max_length=200, nullable=False)
    author_id = ForeignKeyField(to="FKAuthor", nullable=False)


class FKCompositeTarget(BaseModel):
    __tablename__ = "fk_composite_target"
    __pk__        = ("a", "b")
    a = IntField(nullable=False)
    b = IntField(nullable=False)


class FKRefToComposite(BaseModel):
    __tablename__ = "fk_ref_to_composite"
    id        = IntField(primary_key=True)
    target_id = ForeignKeyField(to="FKCompositeTarget", nullable=False)


class FKRefToMissing(BaseModel):
    __tablename__ = "fk_ref_to_missing"
    id      = IntField(primary_key=True)
    ghost_id = ForeignKeyField(to="NoSuchModelXYZ", nullable=False)


class FKPublisher(BaseModel):
    __tablename__ = "fk_publishers"
    id   = IntField(primary_key=True)
    name = StrField(max_length=100, nullable=False)


class FKBookCascade(BaseModel):
    __tablename__ = "fk_books_cascade"
    id           = IntField(primary_key=True)
    title        = StrField(max_length=200, nullable=False)
    publisher_id = ForeignKeyField(to="FKPublisher", nullable=False, on_delete="CASCADE")


class FKBookSetNull(BaseModel):
    __tablename__ = "fk_books_set_null"
    id           = IntField(primary_key=True)
    title        = StrField(max_length=200, nullable=False)
    publisher_id = ForeignKeyField(to="FKPublisher", nullable=True, on_delete="SET NULL")


# ------------------------------------------------------------------ #
#  Fixtures                                                           #
# ------------------------------------------------------------------ #

@pytest.fixture(scope="module", autouse=True)
def setup_db():
    db.configure(
        dialect  = "mysql",
        host     = "127.0.0.1",
        port     = 3307,
        user     = "root",
        password = os.environ.get("DB_PASSWORD", "root"),
        database = "testdb",
        charset  = "utf8mb4",
    )
    with db.connect() as conn:
        cur = conn.cursor()
        cur.execute("DROP TABLE IF EXISTS fk_books")
        cur.execute("DROP TABLE IF EXISTS fk_authors")
        cur.execute("DROP TABLE IF EXISTS fk_ref_to_composite")
        cur.execute("DROP TABLE IF EXISTS fk_composite_target")
        cur.execute("DROP TABLE IF EXISTS fk_books_cascade")
        cur.execute("DROP TABLE IF EXISTS fk_books_set_null")
        cur.execute("DROP TABLE IF EXISTS fk_publishers")
    FKAuthor.create_table()
    FKBook.create_table()
    FKPublisher.create_table()
    FKBookCascade.create_table()
    FKBookSetNull.create_table()
    yield
    with db.connect() as conn:
        cur = conn.cursor()
        cur.execute("DROP TABLE IF EXISTS fk_books")
        cur.execute("DROP TABLE IF EXISTS fk_authors")
        cur.execute("DROP TABLE IF EXISTS fk_ref_to_composite")
        cur.execute("DROP TABLE IF EXISTS fk_composite_target")
        cur.execute("DROP TABLE IF EXISTS fk_books_cascade")
        cur.execute("DROP TABLE IF EXISTS fk_books_set_null")
        cur.execute("DROP TABLE IF EXISTS fk_publishers")
    db.close()


@pytest.fixture(autouse=True)
def clean():
    with db.connect() as conn:
        cur = conn.cursor()
        cur.execute("DELETE FROM fk_books")
        cur.execute("DELETE FROM fk_authors")
        cur.execute("DELETE FROM fk_books_cascade")
        cur.execute("DELETE FROM fk_books_set_null")
        cur.execute("DELETE FROM fk_publishers")
    yield


# ------------------------------------------------------------------ #
#  Field-level SQL generation (no DB)                                 #
# ------------------------------------------------------------------ #

def test_foreignkey_field_emits_plain_column_sql():
    # ForeignKeyField no longer appends a "-- FK -> X" comment — a real
    # constraint is generated by create_table() instead, and a trailing
    # comment would swallow the comma separating it from later columns.
    f = ForeignKeyField(to="FKAuthor", nullable=False)
    f.name = "author_id"
    assert f.to_sql_def("mysql") == "INT NOT NULL"


def test_foreignkey_on_delete_on_update_normalized():
    f = ForeignKeyField(to="FKAuthor", nullable=False, on_delete="cascade", on_update="Cascade")
    assert f.on_delete == "CASCADE"
    assert f.on_update == "CASCADE"


def test_foreignkey_invalid_action_raises():
    with pytest.raises(ValueError, match="not a valid action"):
        ForeignKeyField(to="FKAuthor", nullable=False, on_delete="DROP TABLE")


def test_foreignkey_set_null_requires_nullable():
    with pytest.raises(ValueError, match="must also be nullable"):
        ForeignKeyField(to="FKAuthor", nullable=False, on_delete="SET NULL")


# ------------------------------------------------------------------ #
#  DDL generation                                                      #
# ------------------------------------------------------------------ #

def test_create_table_emits_foreign_key_constraint():
    with db.connect() as conn:
        cur = conn.cursor()
        cur.execute("SHOW CREATE TABLE fk_books")
        ddl = cur.fetchone()[1]
    assert "FOREIGN KEY" in ddl
    assert "REFERENCES" in ddl
    assert "fk_authors" in ddl


def test_create_table_emits_on_delete_cascade():
    with db.connect() as conn:
        cur = conn.cursor()
        cur.execute("SHOW CREATE TABLE fk_books_cascade")
        ddl = cur.fetchone()[1]
    assert "ON DELETE CASCADE" in ddl


def test_create_table_emits_on_delete_set_null():
    with db.connect() as conn:
        cur = conn.cursor()
        cur.execute("SHOW CREATE TABLE fk_books_set_null")
        ddl = cur.fetchone()[1]
    assert "ON DELETE SET NULL" in ddl


# ------------------------------------------------------------------ #
#  DB-level enforcement                                               #
# ------------------------------------------------------------------ #

def test_fk_violation_rejected_by_database():
    with pytest.raises(Exception):
        FKBook.create(title="Orphan", author_id=999999)


def test_fk_valid_insert_succeeds():
    aid = FKAuthor.create(name="Tolkien")
    bid = FKBook.create(title="LOTR", author_id=aid)
    book = FKBook.get(id=bid)
    assert book["author_id"] == aid


def test_fk_on_delete_cascade_removes_child_rows():
    pid = FKPublisher.create(name="Penguin")
    FKBookCascade.create(title="Book A", publisher_id=pid)
    FKBookCascade.create(title="Book B", publisher_id=pid)

    FKPublisher.delete(id=pid)

    assert FKBookCascade.query().where("publisher_id", pid).all() == []


def test_fk_on_delete_set_null_nulls_child_column():
    pid = FKPublisher.create(name="Tor")
    bid = FKBookSetNull.create(title="Book C", publisher_id=pid)

    FKPublisher.delete(id=pid)

    assert FKBookSetNull.get(id=bid)["publisher_id"] is None


def test_fk_navigation_still_works_alongside_constraint():
    # belongs_to/has_many resolve by foreign_key column name, independent
    # of field type — a ForeignKeyField column must still support them.
    aid = FKAuthor.create(name="Asimov")
    bid = FKBook.create(title="Foundation", author_id=aid)
    book   = FKBook.get(id=bid)
    author = book.belongs_to(FKAuthor, foreign_key="author_id")
    assert author["name"] == "Asimov"

    author_row = FKAuthor.get(id=aid)
    books = author_row.has_many(FKBook, foreign_key="author_id")
    assert len(books) == 1
    assert books[0]["title"] == "Foundation"


# ------------------------------------------------------------------ #
#  Error paths                                                        #
# ------------------------------------------------------------------ #

def test_fk_missing_referenced_model_raises():
    with pytest.raises(ValueError, match="could not be found"):
        FKRefToMissing.create_table()


def test_fk_composite_pk_target_raises():
    FKCompositeTarget.create_table()
    try:
        with pytest.raises(ValueError, match="composite primary key"):
            FKRefToComposite.create_table()
    finally:
        with db.connect() as conn:
            conn.cursor().execute("DROP TABLE IF EXISTS fk_composite_target")


# ------------------------------------------------------------------ #
#  YugabyteDB                                                          #
# ------------------------------------------------------------------ #

def _yb_available():
    try:
        s = socket.create_connection(("127.0.0.1", 5433), timeout=2)
        s.close()
        return True
    except OSError:
        return False


yb_skip = pytest.mark.skipif(not _yb_available(), reason="YugabyteDB not running")


class YBFKAuthor(BaseModel):
    __tablename__ = "yb_fk_authors"
    id   = IntField(primary_key=True)
    name = StrField(max_length=100, nullable=False)


class YBFKBook(BaseModel):
    __tablename__ = "yb_fk_books"
    id        = IntField(primary_key=True)
    title     = StrField(max_length=200, nullable=False)
    author_id = ForeignKeyField(to="YBFKAuthor", nullable=False)


def _yb_configure():
    db.close()
    db.configure(
        dialect  = "yugabyte",
        host     = "127.0.0.1",
        port     = 5433,
        user     = "yugabyte",
        password = os.environ.get("YB_PASSWORD", "yugabyte"),
        database = "yugabyte",
    )


def _mysql_configure():
    db.close()
    db.configure(
        dialect  = "mysql",
        host     = "127.0.0.1",
        port     = 3307,
        user     = "root",
        password = os.environ.get("DB_PASSWORD", "root"),
        database = "testdb",
        charset  = "utf8mb4",
    )


def _yb_drop(table: str):
    with db.connect() as conn:
        conn.cursor().execute(f'DROP TABLE IF EXISTS "{table}"')


@yb_skip
def test_yb_fk_constraint_created_and_enforced():
    _yb_configure()
    try:
        _yb_drop("yb_fk_books")
        _yb_drop("yb_fk_authors")
        YBFKAuthor.create_table()
        YBFKBook.create_table()

        with pytest.raises(Exception):
            YBFKBook.create(title="Orphan", author_id=999999)

        aid = YBFKAuthor.create(name="Herbert")
        bid = YBFKBook.create(title="Dune", author_id=aid)
        assert YBFKBook.get(id=bid)["author_id"] == aid
    finally:
        _yb_drop("yb_fk_books")
        _yb_drop("yb_fk_authors")
        _mysql_configure()
